language: python
python:
 - "2.7"
install: pip install -r requirements.txt

before_success:
  - coveralls
  - coverage 
script:
  - pytest --cov
  - coverage 
  - coveralls 
after_success:
  - coveralls
  - coverage 