language: python
python: 
 - "3.6"
install: pip install -r requirements.txt

before_success:
  - coveralls
  - coverage 
script: 
  - pytest tests --cov --cov-report term-missing
  - coverage 
  - coveralls  
after_success:
  - coveralls
  - coverage 

services:
  - postgresql

before_script: 
  - psql -c 'create database ireport_db_test;' -U postgres 

env:
  global:
    - DBNAME=ireport_db_test 